import{a as b,S as q,i as c}from"./assets/vendor-D5TB9rFF.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const v="47378752-b657325f73b86ea506e5db7de",w="https://pixabay.com/api/";async function p(r,t=1,i=15){const s={key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:i};return(await b.get(w,{params:s})).data}const g=document.querySelector("#gallery");let f;function y(r){const t=r.map(({webformatURL:i,largeImageURL:s,tags:e,likes:o,views:n,comments:h,downloads:L})=>`
            <a href="${s}" class="gallery-item">
                <img src="${i}" alt="${e}" />
                <div class="info">
                    <p>Likes: ${o}</p>
                    <p>Views: ${n}</p>
                    <p>Comments: ${h}</p>
                    <p>Downloads: ${L}</p>
                </div>
            </a>
        `).join("");g.innerHTML+=t,f?f.refresh():f=new q(".gallery-item",{captionsData:"alt",captionDelay:250})}function P(){g.innerHTML=""}function l(r){const t=document.querySelector("#load-more");r?t.classList.remove("hidden"):t.classList.add("hidden")}let d="",a=1,u=15;const S=document.querySelector("#search-form"),m=document.querySelector("#loader"),$=document.querySelector("#load-more");S.addEventListener("submit",async r=>{if(r.preventDefault(),d=r.target.elements.query.value.trim(),!d){c.error({message:"Please enter a correct query"});return}a=1,P(),l(!1),m.classList.remove("hidden");try{const t=await p(d,a,u);if(t.hits.length===0){c.info({message:"No images found"});return}y(t.hits),t.totalHits>a*u&&l(!0)}catch{c.error({message:"Error fetching images. Please try again."})}finally{m.classList.add("hidden")}});$.addEventListener("click",async()=>{a++,l(!1);try{const r=await p(d,a,u);y(r.hits),u*a>=r.totalHits?(l(!1),c.info({message:"We're sorry, but you've reached the end of search results."})):l(!0);const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{c.error({message:"Error fetching images. Please try again."})}});
//# sourceMappingURL=index.js.map
