import{a as b,S as q,i as c}from"./assets/vendor-D5TB9rFF.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const v="47378752-b657325f73b86ea506e5db7de",w="https://pixabay.com/api/";async function p(r,t=1,n=15){const s={key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n};return(await b.get(w,{params:s})).data}const g=document.querySelector("#gallery");let f;function h(r){const t=r.map(({webformatURL:n,largeImageURL:s,tags:e,likes:o,views:a,comments:y,downloads:L})=>`
            <a href="${s}" class="gallery-item">
                <img src="${n}" alt="${e}" />
                <div class="info">
                    <p>Likes: ${o}</p>
                    <p>Views: ${a}</p>
                    <p>Comments: ${y}</p>
                    <p>Downloads: ${L}</p>
                </div>
            </a>
        `).join("");g.innerHTML+=t,f?f.refresh():f=new q(".gallery-item",{captionsData:"alt",captionDelay:250})}function P(){g.innerHTML=""}function l(r){const t=document.querySelector("#load-more");r?t.classList.remove("hidden"):t.classList.add("hidden")}let u="",i=1,d=15;const S=document.querySelector("#search-form"),m=document.querySelector("#loader");S.addEventListener("submit",r=>{if(r.preventDefault(),u=r.target.elements.query.value.trim(),!u){c.error({message:"Please enter a correct query"});return}i=1,P(),l(!1),m.classList.remove("hidden"),p(u,i,d).then(t=>{if(t.hits.length===0){c.info({message:"No images found"});return}h(t.hits),t.totalHits>i*d&&l(!0)}).catch(t=>{c.error({message:"Error fetching images. Please try again."})}).finally(()=>{m.classList.add("hidden")})});const $=document.querySelector("#load-more");$.addEventListener("click",()=>{i++,l(!1),p(u,i,d).then(r=>{h(r.hits),d*i>=r.totalHits?(l(!1),c.info({message:"We're sorry, but you've reached the end of search results."})):l(!0);const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}).catch(r=>{c.error({message:"Error fetching images. Please try again."})})});
//# sourceMappingURL=index.js.map
